# Generated by Django 5.2.6 on 2025-11-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_theme_event_food_description_event_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_members',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
