# Generated by Django 5.2.6 on 2025-11-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_event_max_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='host_name',
            field=models.CharField(default='주최자', max_length=100),
        ),
    ]
